// Kratki opisi območij. Pregledaj in dopolni z lokalnim znanjem - to je besedilo,
// po katerem bo Google ločil te strani med sabo.
export const OPISI_REGIJ: Record<string, string> = {
  "pohorje": "Pohorje je obsežno silikatno pogorje med Dravsko in Dravinjsko dolino, kjer prevladujejo smrekovi in bukovi gozdovi med 600 in 1500 metri. Kisla tla in obilne padavine ustrezajo jurčkom in lisičkam, po grebenu pa se razmere zaradi višine razvijejo pozneje kot v dolini.",
  "pohorje-zahod": "Zahodni del Pohorja nad Slovenj Gradcem in Mislinjo je bolj strm in hladnejši od vzhodnega. Gozdovi so pretežno smrekovi z vmesnimi bukovimi sestoji, sezona pa se zaradi višje lege običajno začne pozneje kot na vzhodnem Pohorju.",
  "kozjak": "Kozjak je gričevnato hribovje severno od Drave, obrnjeno proti Avstriji. Mešani gozdovi z bukvijo, smreko in gradnom ter zmerna nadmorska višina pomenijo, da se razmere tu odprejo prej kot na sosednjem Pohorju.",
  "urslja-gora": "Uršlja gora je izrazit vrh nad Slovenj Gradcem in Prevaljami z gozdovi smreke in bukve na strmih pobočjih. Vrh je pogosto v oblaku, zato tla ostajajo vlažna dlje kot v dolini.",
  "pokljuka": "Pokljuka je visoka kraška planota v Julijskih Alpah, pokrita s smrekovimi gozdovi nad 1100 metri. Tla so plitva in kamnita, sezona pa kratka: razmere se odprejo pozno poleti in se ob prvem močnejšem ohladitvi hitro zaprejo.",
  "mezakla": "Mežakla je gozdnata planota med Jesenicami in Bledom, nekoliko nižja in toplejša od Pokljuke. Prevladujeta smreka in bukev, na južnih pobočjih pa je drevesna sestava pestrejša.",
  "jelovica": "Jelovica je kraška planota nad Bohinjsko Belo in Železniki s smrekovimi gozdovi in številnimi vrtačami, kjer se zadržujeta vlaga in hlad. Sezona se začne konec poletja.",
  "velika-planina": "Velika planina in okoliška pobočja Kamniško-Savinjskih Alp so mešanica smrekovih gozdov in planinskih pašnikov. Za gobe je zanimivejši nižji, gozdnati del in ne odprte planine.",
  "menina-planina": "Menina planina je kraška planota med Gornjim Gradom in Tuhinjsko dolino z bukovimi in smrekovimi gozdovi nad 1000 metri. Po kraških tleh voda hitro odteče, zato so za rast pomembna daljša deževna obdobja.",
  "polhograjsko": "Polhograjsko hribovje zahodno od Ljubljane je nizko, razgibano in dobro dostopno. Prevladujejo bukovi gozdovi s primesjo smreke in kostanja, razmere pa se zaradi nizke lege odprejo zgodaj.",
  "krim": "Krim se dviga nad Ljubljanskim barjem in je pokrit z bukovimi gozdovi na kraški podlagi. Zaradi bližine Ljubljane je obiska veliko, zato se splača iti zgodaj zjutraj ali stran od glavnih poti.",
  "posavsko-hribovje": "Posavsko hribovje med Litijo, Zagorjem in Trbovljami je gričevnat svet z mešanimi gozdovi bukve, gradna in smreke. Lege so raznolike, zato se razmere med grapami in slemeni precej razlikujejo.",
  "kozjansko": "Kozjansko je gričevje med Savinjo in Sotlo z mešanimi listnatimi gozdovi, v katerih prevladujeta bukev in hrast. Nizka nadmorska višina pomeni zgodnjo sezono, v vročih poletjih pa se tla hitro izsušijo.",
  "bohor": "Bohor je gozdnato sleme nad Senovim in Planino pri Sevnici z bukovimi in mešanimi gozdovi. Severna pobočja ostanejo vlažna dlje kot prisojna južna.",
  "haloze": "Haloze so gričevje ob Dravinji in meji s Hrvaško, kjer se gozdovi menjavajo z vinogradi in travniki. Prevladujeta hrast in kostanj, kar ustreza vrstam, ki imajo rade toplejša in svetlejša rastišča.",
  "slovenske-gorice": "Slovenske gorice so nizko gričevje med Dravo in Muro z gozdnimi otoki med njivami in vinogradi. Gozdovi so listnati, pretežno hrastovi in bukovi, razmere pa so močno odvisne od poletnih neviht.",
  "goricko": "Goričko je nizko, prostrano gričevje v Prekmurju z mešanimi gozdovi, kjer prevladujeta hrast in bor. Goričko dobi najmanj padavin v Sloveniji, zato so sušna obdobja pogosta, po izdatnem dežju pa se razmere odprejo hitro.",
  "gorjanci": "Gorjanci se dvigajo nad Novim mestom proti hrvaški meji in so pokriti z obsežnimi bukovimi gozdovi. Višji in hladnejši del ostane vlažen tudi takrat, ko je v dolini že suho.",
  "bela-krajina": "Bela krajina je nizek kraški svet z brezovimi, hrastovimi in borovimi gozdovi na plitvih tleh. Tla se hitro izsušijo, zato je tu dež zadnjih tednov še pomembnejši kot drugod.",
  "kocevski-rog": "Kočevski Rog je obsežno kraško pogorje z dinarskimi jelovo-bukovimi gozdovi in redkimi naselji. Znotraj njega je pragozdni ostanek Rajhenavski Rog, ki je gozdni rezervat s posebnim režimom, okoliški gozdovi pa veljajo za enega najbolj gobarskih predelov Slovenije.",
  "goteniska-gora": "Goteniška gora nad Kočevsko Reko je visok, hladen kraški svet z jelovo-bukovimi gozdovi. Sezona se začne pozneje kot v Beli krajini, zato pa traja globlje v jesen.",
  "loska-dolina": "Loška dolina pod Snežnikom je obdana z jelovo-bukovimi gozdovi na kraški podlagi. Dno kotline se ponoči močno ohladi, zato jeseni rast tam poteka počasneje kot na pobočjih.",
  "bloke": "Bloška planota je visoka kraška planota nad 700 metri s smrekovimi in bukovimi gozdovi ter travniki. Zaradi mrazišč se sezona konča prej kot v okoliških, nižje ležečih krajih.",
  "sneznik": "Snežniški gozdovi so eden največjih sklenjenih gozdnih kompleksov v Sloveniji, večinoma jelovo-bukovi sestoji na apnencu. Del območja pokriva gozdni rezervat Snežnik-Ždrocle, največji pri nas in od leta 2017 na Unescovem seznamu svetovne dediščine, kjer je poseganje v gozd omejeno. Drugod so razmere za rast med najbolj stabilnimi v državi.",
  "javorniki": "Javorniki nad Cerkniškim jezerom so kraško hribovje z jelovo-bukovimi gozdovi in številnimi vrtačami. V vrtačah se zadržujeta vlaga in hlad, zato so razlike že na kratkih razdaljah velike.",
  "nanos": "Nanos je kraška planota nad Vipavsko dolino, izpostavljena burji in soncu. Bukovi gozdovi na severnih pobočjih zadržujejo vlago, na južnih in kamnitih legah pa se tla hitro izsušijo.",
  "brkini": "Brkini so flišno gričevje med Krasom in Čičarijo, edini nekraški otok v tem delu Slovenije. Flišna tla zadržujejo vodo bolje kot okoliški kras, zato se rast po dežju hitreje odzove.",
  "trnovski-gozd": "Trnovski gozd je visoka kraška planota nad Vipavsko dolino z bukovimi in jelovimi gozdovi. Zaradi obilnih padavin in znanih mrazišč so razmere pogosto ugodne tudi takrat, ko je drugod na Primorskem suho.",
  "idrijsko": "Idrijsko in Cerkljansko je strm, gozdnat svet z bukovimi in jelovimi sestoji nad globokimi dolinami. Padavin je veliko, lege pa zelo raznolike, zato se splača primerjati sosednja pobočja.",
  "kolovrat": "Kolovrat je sleme nad dolino Soče proti italijanski meji, pokrito z mešanimi bukovimi gozdovi in kostanjem. Zahodne lege dobijo največ padavin, kadar se fronte ustavijo ob alpski pregradi.",
};

export const opisRegije = (slug: string) => OPISI_REGIJ[slug] ?? null;
